config/routes.rb
Rails.application.routes.draw do
  root to: "appointments#index"

  resources :appointments, except: [:edit, :new]

  resources :reports, only: [:index, :new, :create, :show, :update, :destroy] do
    collection do
      get :generate
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :patients do
    resources :notes, only: [:show, :new, :create, :update, :destroy]
    resources :pathologies, only: [:show, :new, :create, :update, :destroy]

    member do
      post :upload_ordonnance
      delete :destroy_ordonnance
    end
  end

  get "profile", to: "users#profile"
end

app/models/pathology.rb
class Pathology < ApplicationRecord
  belongs_to :patient
end

app/controllers/pathologies_controller.rb
class PathologiesController < ApplicationController
  before_action :set_patient
  before_action :set_pathology, only: [:show, :edit, :update, :destroy]


  def index
    @pathologies = @patient.pathologies
  end

  def new
    @pathology = @patient.pathologies.new
  end

  def create
    @pathology = @patient.pathologies.new(pathology_params)
    if @pathology.save
      redirect_to patient_path(@patient), notice: 'Pathologie créée avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @pathology.update(pathology_params)
      redirect_to patient_path(@patient), notice: 'Pathologie mise à jour avec succès.'
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @pathology.destroy!
    redirect_to patient_path(@patient), notice: 'Pathologie supprimée avec succès.'
  end

  private

  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  def set_pathology
    @pathology = Pathology.find(params[:id])
  end

  def pathology_params
    params.require(:pathology).permit(:description)
  end
end

app/views/pathologies/new.html.erb
<div class="mb-3 p-2">
  <%= link_to patient_path(@patient), class: "text-decoration-none" do %>
    <i class="text-muted symbol fa-solid fa-reply"></i>
  <% end %>
</div>

<div class="container">
  <h5>Nouvelle pathologie pour <%= @patient.name %></h5>

  <%= simple_form_for [@patient, @pathology] do |f| %>
    <%= f.input :description, label: "Description de la pathologie" %>
    <div class="text-end">
      <%= f.button :submit, "Créer la pathologie", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/pathologies/show.html.erb
<div class="mb-3 p-2">
  <%= link_to patient_path(@patient), class: "text-decoration-none" do %>
    <i class="text-muted symbol fa-solid fa-reply"></i>
  <% end %>
</div>

<div class="container">
  <div class="d-flex justify-content-between">
    <h5 class="mb-3">Pathologie de <%= @patient.name %></h5>
    <%= link_to patient_pathology_path(@patient, @pathology), class:"text-decoration-none", data: {turbo_method: :delete, turbo_confirm: 'Êtes-vous sûr?'} do %>
      <i class="text-muted fa-solid fa-trash"></i>
    <% end %>
  </div>
    <%= simple_form_for [@patient, @pathology] do |f| %>
      <%= f.input :description, label: false, input_html: { class: "remove-validation" } %>
      <div class="text-end">
        <%= f.submit "Mettre à jour", class: "btn btn-primary" %>
      </div>
    <% end %>
</div>